global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@creative-platform.com'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'

# Routing configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 15m
    
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 4h
    
    - match:
        alertname: HighErrorRate
      receiver: 'error-alerts'
      group_wait: 5s
      repeat_interval: 10m
    
    - match:
        alertname: DatabaseConnectionFailure
      receiver: 'database-alerts'
      group_wait: 1s
      repeat_interval: 5m

# Inhibition rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

# Receiver definitions
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/'

  - name: 'critical-alerts'
    email_configs:
      - to: 'devops@creative-platform.com'
        subject: '🔴 CRITICAL ALERT: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          
          Details:
          {{ range .Alerts }}
          - Instance: {{ .Labels.instance }}
          - Description: {{ .Annotations.description }}
          - Started: {{ .StartsAt }}
          {{ end }}
          
          Dashboard: http://grafana.creative-platform.com/d/app-dashboard
        headers:
          Priority: 'high'
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#critical-alerts'
        title: '🔴 Critical Alert'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          *Instance:* {{ .Labels.instance }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        actions:
          - type: button
            text: 'View Dashboard'
            url: 'http://grafana.creative-platform.com/d/app-dashboard'
    
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.description }}'
        severity: 'critical'

  - name: 'warning-alerts'
    email_configs:
      - to: 'devops@creative-platform.com'
        subject: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          
          Details:
          {{ range .Alerts }}
          - Instance: {{ .Labels.instance }}
          - Description: {{ .Annotations.description }}
          - Started: {{ .StartsAt }}
          {{ end }}
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#monitoring'
        title: '⚠️ Warning Alert'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          *Instance:* {{ .Labels.instance }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  - name: 'error-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#errors'
        title: '🚨 High Error Rate Detected'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Error Rate:* {{ .CommonAnnotations.description }}
          
          Immediate action required!
        actions:
          - type: button
            text: 'View Logs'
            url: 'http://kibana.creative-platform.com'
          - type: button
            text: 'View Metrics'
            url: 'http://grafana.creative-platform.com/d/app-dashboard'

  - name: 'database-alerts'
    email_configs:
      - to: 'dba@creative-platform.com'
        subject: '🔴 DATABASE ALERT: {{ .GroupLabels.alertname }}'
        body: |
          URGENT: Database connectivity issue detected
          
          Alert: {{ .GroupLabels.alertname }}
          {{ range .Alerts }}
          - Database: {{ .Labels.database }}
          - Instance: {{ .Labels.instance }}
          - Description: {{ .Annotations.description }}
          - Started: {{ .StartsAt }}
          {{ end }}
          
          Please investigate immediately.
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#database'
        title: '🔴 Database Alert'
        text: |
          *URGENT: Database connectivity issue*
          
          *Alert:* {{ .GroupLabels.alertname }}
          {{ range .Alerts }}
          *Database:* {{ .Labels.database }}
          *Instance:* {{ .Labels.instance }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

# Templates for custom messages
templates:
  - '/etc/alertmanager/templates/*.tmpl'