global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Frontend Application
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Backend API
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # AI Services
  - job_name: 'ai-services'
    static_configs:
      - targets: ['ai-services:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # NGINX
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Queue Metrics
  - job_name: 'queue-worker'
    static_configs:
      - targets: ['queue-worker:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Application Performance Monitoring
  - job_name: 'app-performance'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 60s

  # Custom Business Metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/api/v1/metrics/business'
    scrape_interval: 300s # 5 minutes